// =============================================================================
// Awlad Yahya Factory - Synchronized Product Catalog Data
// Auto-generated from: data/Awlad_Yahya_Product_Catalog_Database.xlsx
// Generated at: 2026-09-22 00:51:11
// =============================================================================

window.categoriesData = [
    {
        "id":  "BC",
        "name":  "كراسي حلاقة وكوافير",
        "description":  "كراسي حلاقة رجالي و كراسى كوافير حريمى وصالونات تجميل بمواصفات احترافية",
        "image":  "assets/categories/barber-chairs.webp",
        "displayOrder":  1,
        "active":  true,
        "featured":  true,
        "seoTitle":  "كراسي حلاقة وكوافير | مصنع أولاد يحيى",
        "seoDescription":  "أفضل تشكيلة كراسي حلاقة هيدروليك وكوافير في مصر من مصنع أولاد يحيى بتصنيع عالي الجودة, كراسى حلاقه لوكس و ثابت و كراسى باكم."
    },
    {
        "id":  "KC",
        "name":  "كراسي أطفال",
        "description":  "كراسي حلاقة مخصصة للأطفال بتصميمات جذابة وآمنة",
        "image":  "assets/categories/kids-chairs.webp",
        "displayOrder":  2,
        "active":  true,
        "featured":  false,
        "seoTitle":  "كراسي حلاقة أطفال | مصنع أولاد يحيى",
        "seoDescription":  "تشكيلة كراسي حلاقة أطفال بأمان تام وتصميمات تناسب صالونات الحلاقة."
    },
    {
        "id":  "SH",
        "name":  "أحواض غسيل الشعر",
        "description":  "أحواض غسيل شعر وسيراميك متين لصالونات التجميل والحلاقة",
        "image":  "assets/categories/shampoo-units.webp",
        "displayOrder":  3,
        "active":  true,
        "featured":  true,
        "seoTitle":  "أحواض غسيل شعر وصالونات | أولاد يحيى",
        "seoDescription":  "وحدات غسيل شعر متكاملة مع احواض بورسلين وخامات مقاومة للمياه."
    },
    {
        "id":  "CH",
        "name":  "شيزلونجات",
        "description":  "شيزلونجات مساج وتنظيف بشرة متعددة الاستخدامات",
        "image":  "assets/categories/chaise-lounges.webp",
        "displayOrder":  4,
        "active":  true,
        "featured":  false,
        "seoTitle":  "شيزلونجات صالونات ومراكز تجميل | أولاد يحيى",
        "seoDescription":  "شيزلونجات احترافية لصالونات التجميل ومراكز العناية."
    },
    {
        "id":  "EQ",
        "name":  "مستلزمات وتجهيزات الصالونات",
        "description":  "تجهيزات ومعدات متكاملة لافتتاح وتجديد صالونات الحلاقة",
        "image":  "assets/categories/equipment.webp",
        "displayOrder":  5,
        "active":  true,
        "featured":  false,
        "seoTitle":  "تجهيزات ومعدات صالونات حلاقة | أولاد يحيى",
        "seoDescription":  "كافة مستلزمات وتجهيزات صالونات الحلاقة ومراكز التجميل من المصنع مباشرة."
    }
];

window.productsData = [
    {
        "id":  "BC-031",
        "code":  "AY-28",
        "name":  "ملكى حديث فضى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  1,
        "price":  "8700",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-031/main.webp",
        "images":  [
                       "assets/products/BC-031/main.webp",
                       "assets/products/BC-031/angle-1.jpg",
                       "assets/products/BC-031/angle-2.jpg"
                   ],
        "specifications":  "مضخة هيدروليك دائرية قوية، دوران 360 درجة، نظام إمالة ظهر هيدروليكي متعدد المستويات، مسند رأس قابل للتعديل والفك، مسند أرجل متين مدعم بكاوتش مانع للانزلاق",
        "materials":  "شاسيه حديد ثقيل معالج عالي الصلابة، إكسسوارات وقاعدة صينية نيكل كروم ثقيلة ، فوم وإسفنج كابوتنيه عالي الكثافة، جلد فاخر مستورد معالج ضد التقشير والتشقق",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "مرحباً، أود الاستفسار عن كود المنتج: AY-05 (الكرسي الملكي المصري الكلاسيك هيدروليك) المعروض على موقعكم.",
        "seoTitle":  "كرسي حلاقة رجالي كلاسيك الملكي المصري هيدروليك | مصنع أولاد يحيى",
        "seoDescription":  "اكتشف الكرسي الملكي المصري الكلاسيك من مصنع أولاد يحيى، تصميم بريميوم يجمع بين فخامة الكلاسيك وقوة التحمل، هيدروليك عالي الجودة ينافس المستورد وبأفضل سعر مصنع في مصر.",
        "keywords":  "كرسي حلاقة كلاسيك، الكرسي الملكي المصري، كراسي حلاقة رجالي، كرسي حلاقة هيدروليك، مصنع أولاد يحيى، تجهيز صالونات حلاقة، كراسي باربر شوب، كراسي حلاقة مستوردة ومحلية"
    },
    {
        "id":  "BC-030",
        "code":  "AY-27",
        "name":  "ملكى مصرى كبير استانليس بالكامل ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  2,
        "price":  "12000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-030/main.webp",
        "images":  [
                       "assets/products/BC-030/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-032",
        "code":  "AY-29",
        "name":  "ملكى حديث ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  3,
        "price":  "10000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-032/main.webp",
        "images":  [
                       "assets/products/BC-032/main.webp",
                       "assets/products/BC-032/angle-1.jpg",
                       "assets/products/BC-032/angle-2.jpg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-029",
        "code":  "AY-26",
        "name":  "ملكى مصرى كبير استانليس بالكامل فضى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  4,
        "price":  "11000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-029/main.webp",
        "images":  [
                       "assets/products/BC-029/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-003",
        "code":  "AY-025",
        "name":  "شبك ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "كرسي حريمي موديل \"الشبك\" – لمسة شياكة وفخامة لصالونك من مصنع أولاد يحيى!\r\nكرسي كوافير بتصميم عصري راقي مع طلاء PVD دهبي فخم وعالي الجودة، مزود بهيدروليك قوي وسلس، وتنجيد إسفنج عالي الكثافة مع جلد متين سهل التنظيف وضد التقشير ليتحمل ضغط الشغل اليومي ويدوم معاك سنين.",
        "fullDescription":  "كرسي كوافير حريمي موديل \"الشبك\" الدهبي | مصنع أولاد يحيى لتصنيع كراسي الحلاقة\r\n\r\nلو بتدوري/بتدور على قطعة تجمع بين الشياكة المطلقة والعملية والتحمل، كرسي \"الشبك\" هو الاختيار المثالي اللي هيضيف لمسة ديكور فاخرة لأي بيوتي سنتر أو صالون حريمي.\r\n\r\nأهم مميزات ومواصفات الكرسي:\r\n\r\nتصميم عصري مميز: ظهر بتصميم شبكي أنيق ومودرن مع خياطة كابوتنيه راقية على المقعد والمسند بتدي شكل شيك جداً ومريح في نفس الوقت.\r\n\r\nطلاء دهبي PVD عالي الجودة: معالج بالكامل ضد الصدأ والخدوش ومقاوم للرطوبة والمواد الكيماوية عشان يفضل محتفظ بلمعته ورونقه على المدى الطويل.\r\n\r\nهيدروليك قوي وسلس: بيتحمل الأوزان الثقيلة وبيديك تحكم مرن في الرفع والنزول بكل سهولة أثناء الشغل.\r\n\r\nتنجيد وإسفنج عالي الكثافة: مريح جداً للزبونة في الجلسات الطويلة، ومبيبطش ولا يغير شكله مع كثرة الاستخدام.\r\n\r\nجلد ممتاز وفاخر: خامة متينة جداً، ضد التقشير وسهل التنظيف والتعقيم بعد كل عميلة بدون ما يتأثر.\r\n\r\nقاعدة متزنة وثابتة: صينية دائرية دهبية واسعة تضمن ثبات الكرسي 100% مع مسند مريح للقدمين.",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  5,
        "price":  "6000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-03/main.webp",
        "images":  [
                       "assets/products/BC-03/main.webp",
                       "assets/products/BC-03/angle-1.jpg"
                   ],
        "specifications":  "مضخة هيدروليك دائرية، دوران 360 درجة، إمالة حتى 135 درجة",
        "materials":  "",
        "availableColors":  "أسود، بني، جملي, اوف وايت, كشمير",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "كرسي كوافير حريمي هيدروليك موديل الشبك دهبي PVD | مصنع أولاد يحيى",
        "seoDescription":  "احصل على كرسي كوافير حريمي موديل الشبك هيدروليك من مصنع أولاد يحيى، طلاء PVD دهبي فاخر عالي الجودة ضد الصدأ، إسفنج عالي الكثافة وجلد متين سهل التنظيف وضد التقشير بأفضل سعر.",
        "keywords":  "كرسي كوافير، كرسي كوافير حريمي، كرسي الشبك، كراسي صالونات تجميل، كراسي بيوتي سنتر، كرسي هيدروليك دهبي، طلاء PVD، مصنع أولاد يحيى، لوازم كوافير، تجهيز صالونات حريمي"
    },
    {
        "id":  "BC-009",
        "code":  "AY-08",
        "name":  "كرسى تفاحه دواسه كاوتش",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "كرسي حلاقة رجالي موديل \"التفاحة\" – الراحة والقوة اللي صالونك محتاجها من مصنع أولاد يحيى!\r\n\r\nكرسي مصمم خصيصاً ليتحمل أقصى درجات ضغط الشغل اليومي، مزود بهيدروليك قوي وسلس، وإمكانية إمالة الظهر ومسند رأس متحرك لجلسات حلاقة وتنظيف بشرة مريحة جداً لزبونك، مع تنجيد إسفنج عالي الكثافة وجلد مستورد متين ومقاوم للتقشير.",
        "fullDescription":  "كرسي حلاقة رجالي هيدروليك موديل \"التفاحة\" | تصنيع مصنع أولاد يحيى لكراسي الحلاقة\r\n\r\nلو بتجهز صالون حلاقة رجالي وبتبحث عن المتانة والعملية والراحة الفائقة، موديل \"التفاحة\" هو خيارك الأنسب والأكثر اعتمادية؛ تصميم مريح ومدروس يدعم ظهر الزبون ويديك حرية وسهولة كاملة أثناء الشغل.\r\n\r\nأهم مواصفات ومميزات الموديل:\r\n\r\nهيدروليك فائق التحمل: بستم هيدروليك قوي ناعم في الحركة وسهل الرفع والنزول بدون أي مجهود، مع دوران 360 درجة وثبات تام.\r\n\r\nإمالة الظهر وتعدد الأوضاع: إمكانية نزول الظهر بزاوية مريحة جداً لخدمات الدقن، الفتلة، وماسكات تنظيف البشرة.\r\n\r\nمسند رأس متحرك (مخدة): قابلة للتعديل والرفع والنزول لتناسب كل أطوال الزبائن وتوفير أقصى درجات الراحة للرقبة.\r\n\r\nتنجيد وإسفنج صب عالي الكثافة: إسفنج مريح وعملي يحتفظ بمرونته وارتفاعه ومبيبطش مع كثرة الاستخدام والسنوات.\r\n\r\nجلد صناعي عالي الجودة: خامة ممتازة مقاومة للتشقق والتقشير، سهلة المسح والتعقيم المستمر ومقاومة للمياه والمواد المستخدمة في الصالون.\r\n\r\nقاعدة حديد مدعمة بالكروم: صينية دائرية ثقيلة تضمن اتزان الكرسي التام وعدم اهتزازه مع مسند قدم قوي ومريح.\r\n\r\n📞 للحجز والاستفسار وطلب الأوردر مباشرة:\r\n\r\nتواصل معنا عبر الهاتف أو واتساب: 201008355616+\r\n\r\n🌐 لمشاهدة أحدث موديلاتنا وتحميل الكتالوج بالكامل:\r\n\r\nhttps://wa.me/c/201064116703\r\n\r\n📲 صفحتنا الرسمية على فيسبوك:\r\n\r\nhttps://www.facebook.com/YahiaSonsCosmetics\r\n\r\n📢 تابع عروضنا وخامات المصنع على التليجرام:\r\n\r\nhttps://t.me/YahiaSons",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  6,
        "price":  "5500",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-09/main.webp",
        "images":  [
                       "assets/products/BC-09/main.webp"
                   ],
        "specifications":  "هيدروليك رفع وخفض سلس، دوران 360 درجة، إمكانية إمالة الظهر لمستويات متعددة، مسند رأس متحرك وقابل للتعديل، مسند قدم متين ومريح",
        "materials":  "شاسيه حديد متين عالي التحمل، قاعدة دائرية كروم ثقيلة مضادة للانزلاق، جلد مستورد فاخر ضد التقشير وسهل التنظيف، إسفنج سوفت عالي الكثافة",
        "availableColors":  "أسود، بني، جملي, اوف وايت, كشمير",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "مرحباً، أود الاستفسار عن رسى التفاحه (كرسي حلاقة رجالي موديل التفاحة هيدروليك) المعروض على موقعكم.",
        "seoTitle":  "كرسي حلاقة رجالي هيدروليك موديل التفاحة | مصنع أولاد يحيى",
        "seoDescription":  "اشتري كرسي حلاقة رجالي موديل التفاحة هيدروليك من مصنع أولاد يحيى، شاسيه حديد قوي، إمالة ظهر ومسند رأس متحرك، إسفنج عالي الكثافة وجلد فاخر يتحمل ضغط الشغل بأفضل سعر مصنع.",
        "keywords":  "كرسي حلاقة، كرسي حلاقة رجالي، كرسي التفاحة، كراسي صالونات حلاقة، كرسي هيدروليك، مصنع أولاد يحيى، تجهيز صالونات رجالي، كراسي حلاقة هيدروليك، لوازم كوافير وحلاقة"
    },
    {
        "id":  "BC-010",
        "code":  "AY-09",
        "name":  "تمساح دواسه معدن",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  7,
        "price":  "5400",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-010/main.webp",
        "images":  [
                       "assets/products/BC-010/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-012",
        "code":  "AY-12",
        "name":  "كريستال دواسه كوتش",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  8,
        "price":  "5900",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-012/main.webp",
        "images":  [
                       "assets/products/BC-012/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-013",
        "code":  "AY-13",
        "name":  "كرسي رويال هيدروليك مدور (Royal Round) ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  9,
        "price":  "7200",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-013/main.webp",
        "images":  [
                       "assets/products/BC-013/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-014",
        "code":  "AY-13B",
        "name":  "كرسي رويال هيدروليك مدور (Royal Round) فضى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  10,
        "price":  "6900",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-014/main.webp",
        "images":  [
                       "assets/products/BC-014/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-001",
        "code":  "AY-01",
        "name":  "كرسى ثابت عادى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "الكرسى الدبابه الثابت , خامات قويه و يعيش سنين, مناسب لصالونات الحلاقة الرجالي.",
        "fullDescription":  "كرسي حلاقة رجالي , الكرسى الدبابه صُمم خصيصًا ليتحمل ضغط الشغل الشاق والمستمر داخل الصالونات المزدحمة. يعتمد الكرسي على شاسيه حديد متين وقاعدة ثابتة تمنحه أقصى درجات الاتزان والأمان أثناء العمل اليومي، مع خامات عالية الجودة  تضمن بقاءه لسنوات طويلة دون تأثر. مزود بتنجيد مريح وفوم كثيف لتوفير راحة مثالية للزبون أثناء جلسات الحلاقة الطويلة، ليكون الاستثمار الأضمن والعملي لكل صاحب صالون يبحث عن القوة والاعتمادية دون قلق من الأعطال.",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  11,
        "price":  "2650",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-01/main.webp",
        "images":  [
                       "assets/products/BC-01/main.webp"
                   ],
        "specifications":  "",
        "materials":  "شاسيه حديد معالج، جلد صناعي عالي التحمل، فوم كثافة عالية",
        "availableColors":  "أسود، بني، جملي",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "مرحبًا، أود الاستفسار عن كود المنتج: AY-01 (كرسى ثابت عادى) المعروض على موقعكم.",
        "seoTitle":  "كرسي حلاقة كلاسيك هيدروليك | مصنع أولاد يحيى",
        "seoDescription":  "احصل على كرسي حلاقة كلاسيك هيدروليك من مصنع أولاد يحيى. متانة عالية وتصميم مريح.",
        "keywords":  "كرسي حلاقة, كراسي صالونات, كراسي هيدروليك, أولاد يحيى"
    },
    {
        "id":  "BC-002",
        "code":  "AY-02",
        "name":  "كرسى لوكس دواسه عريضه",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "كرسى لوكس دواسه عريضه - كرسى عملى و اقتصادى",
        "fullDescription":  "كرسي حلاقة رجالي , الكرسى اللوكس , صُمم خصيصًا ليتحمل ضغط الشغل الشاق والمستمر داخل الصالونات المزدحمة. يعتمد الكرسي على شاسيه حديد متين وقاعدة ثابتة تمنحه أقصى درجات الاتزان والأمان أثناء العمل اليومي، مع خامات عالية الجودة  تضمن بقاءه لسنوات طويلة دون تأثر. مزود بتنجيد مريح وفوم كثيف لتوفير راحة مثالية للزبون أثناء جلسات الحلاقة الطويلة، ليكون الاستثمار الأضمن والعملي لكل صاحب صالون يبحث عن القوة والاعتمادية دون قلق من الأعطال.",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  12,
        "price":  "2900",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-02/main.webp",
        "images":  [
                       "assets/products/BC-02/main.webp"
                   ],
        "specifications":  "",
        "materials":  "جلد فاخر، قاعدة نيكل كروم",
        "availableColors":  "أسود، رمادي، بيج",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "مرحبًا، أود الاستفسار عن كود المنتج: AY-02 (كرسى لوكس دواسه عريضه) المعروض على موقعكم.",
        "seoTitle":  "كرسي كوافير عصري | مصنع أولاد يحيى",
        "seoDescription":  "كرسي كوافير وصالونات تجميل بتصميم حديث وجودة تصنيع مصرية فائقة.",
        "keywords":  "كرسي كوافير, كراسي تجميل, صالونات حريمي"
    },
    {
        "id":  "BC-016",
        "code":  "AY-14",
        "name":  "موزه باكم كبير ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  13,
        "price":  "6500",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-016/main.webp",
        "images":  [
                       "assets/products/BC-016/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-019",
        "code":  "AY-16",
        "name":  "موزه باكم كبير فضى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  14,
        "price":  "6000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-019/main.webp",
        "images":  [
                       "assets/products/BC-019/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-020",
        "code":  "AY-17",
        "name":  "موزه حريمى فضى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  15,
        "price":  "5500",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-020/main.webp",
        "images":  [
                       "assets/products/BC-020/main.webp",
                       "assets/products/BC-012/angle-1.jpg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-018",
        "code":  "AY-15",
        "name":  "موزه حريمى ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  16,
        "price":  "5900",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-018/main.webp",
        "images":  [
                       "assets/products/BC-018/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-021",
        "code":  "AY-19",
        "name":  "مربع يد استانليس باكم حريمى فضى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  17,
        "price":  "5500",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-021/main.webp",
        "images":  [
                       "assets/products/BC-021/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-022",
        "code":  "AY-20",
        "name":  "مربع يد استانليس باكم كبير فضى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  18,
        "price":  "6000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-022/main.webp",
        "images":  [
                       "assets/products/BC-022/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-025",
        "code":  "AY-23",
        "name":  "مربع اقتصادى فضى اسود",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  19,
        "price":  "3900",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-025/main.webp",
        "images":  [
                       "assets/products/BC-025/main.webp",
                       "assets/products/BC-025/angle-1.jpg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-026",
        "code":  "AY-23B",
        "name":  "مربع اقتصادى فضى جلد مختلف",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  20,
        "price":  "4000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-026/main.webp",
        "images":  [
                       "assets/products/BC-026/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-023",
        "code":  "AY-21",
        "name":  "مربع يد استانليس باكم حريمى ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  21,
        "price":  "5900",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-023/main.webp",
        "images":  [
                       "assets/products/BC-023/main.webp",
                       "assets/products/BC-023/detail.jpg",
                       "assets/products/BC-023/angle-1.jpg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-024",
        "code":  "AY-22",
        "name":  "مربع يد استالنليس باكم كبير ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  22,
        "price":  "6400",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-024/main.webp",
        "images":  [
                       "assets/products/BC-024/main.webp",
                       "assets/products/BC-024/angle-1.jpg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-028",
        "code":  "AY-23GOLD",
        "name":  "مربع اقتصادى ذهبى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  23,
        "price":  "4100",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-028/main.webp",
        "images":  [
                       "assets/products/BC-028/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-033",
        "code":  "AY-34",
        "name":  "كرسى الورده",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  24,
        "price":  "4400",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-033/main.webp",
        "images":  [
                       "assets/products/BC-033/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-034",
        "code":  "AY-35",
        "name":  "كرسى الفنجان",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  25,
        "price":  "4500",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-034/main.webp",
        "images":  [
                       "assets/products/BC-034/main.webp",
                       "assets/products/BC-034/angle-1.jpg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "CH-01",
        "code":  "AY-B1",
        "name":  "شازلونج",
        "category":  "CH",
        "categoryName":  "شيزلونجات",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  26,
        "price":  "3300",
        "showPrice":  "Yes",
        "image":  "assets/products/CH-01/main.webp",
        "images":  [
                       "assets/products/CH-01/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "CH-02",
        "code":  "AY-C01",
        "name":  "كرسى قاعده نجمه للشازلونج",
        "category":  "CH",
        "categoryName":  "شيزلونجات",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  27,
        "price":  "1500",
        "showPrice":  "Yes",
        "image":  "assets/products/CH-02/main.webp",
        "images":  [
                       "assets/products/CH-02/main.webp",
                       "assets/products/CH-02/angle-1.jpg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-036",
        "code":  "AY-LUX31",
        "name":  "طياره بنتلى",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  28,
        "price":  "11000",
        "showPrice":  "Yes",
        "image":  "assets/products/BC-036/main.webp",
        "images":  [
                       "assets/products/BC-036/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "CH-03",
        "code":  "AY-P01",
        "name":  "كرسى بدكير بالبف",
        "category":  "CH",
        "categoryName":  "شيزلونجات",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  29,
        "price":  "5500",
        "showPrice":  "Yes",
        "image":  "assets/products/CH-03/main.webp",
        "images":  [
                       "assets/products/CH-03/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "SH-02",
        "code":  "AY-W02",
        "name":  "حوض غسيل بورسلين ذهبى",
        "category":  "SH",
        "categoryName":  "أحواض غسيل الشعر",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  30,
        "price":  "7000",
        "showPrice":  "Yes",
        "image":  "assets/products/SH-02/main.webp",
        "images":  [
                       "assets/products/SH-02/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "SH-03",
        "code":  "AY-W03",
        "name":  "حوض غسيل بورسلين فضى",
        "category":  "SH",
        "categoryName":  "أحواض غسيل الشعر",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  31,
        "price":  "6900",
        "showPrice":  "Yes",
        "image":  "assets/products/SH-03/main.webp",
        "images":  [
                       "assets/products/SH-03/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "SH-04",
        "code":  "AY-W04",
        "name":  "حوض غسيل بورسلين بدون اكسسوار",
        "category":  "SH",
        "categoryName":  "أحواض غسيل الشعر",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  32,
        "price":  "6600",
        "showPrice":  "Yes",
        "image":  "assets/products/SH-04/main.webp",
        "images":  [
                       "assets/products/SH-04/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "SH-01",
        "code":  "AY-W01",
        "name":  "حوض غسيل شعبى",
        "category":  "SH",
        "categoryName":  "أحواض غسيل الشعر",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  33,
        "price":  "2300",
        "showPrice":  "Yes",
        "image":  "assets/products/SH-01/main.webp",
        "images":  [
                       "assets/products/SH-01/main.webp"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "KC-001",
        "code":  "AY-K01",
        "name":  "كرسي حلاقة أطفال شكل سيارة ",
        "category":  "KC",
        "categoryName":  "كراسي أطفال",
        "shortDesc":  "كرسي حلاقة مخصص للأطفال على شكل سيارة ألعاب.",
        "fullDescription":  "موديل اختباري لتوضيح منتجات الأطفال المزودة بأحزمة أمان وتأثيرات ضوئية وموسيقية لجذب الأطفال أثناء الحلاقة.",
        "status":  "Available",
        "featured":  "Yes",
        "displayOrder":  34,
        "price":  "6200",
        "showPrice":  "Yes",
        "image":  "assets/products/KC-001/main.webp",
        "images":  [
                       "assets/products/KC-001/main.webp",
                       "assets/products/KC-001/angle-1.jpg",
                       "assets/products/KC-001/angle-2.jpg"
                   ],
        "specifications":  "حزام أمان، مضخة رفع هيدروليك، أضواء وأصوات ترفيهية",
        "materials":  "فايبر جلاس مقوى، قاعدة حديد متينة",
        "availableColors":  "أحمر، أزرق، أصفر",
        "customizationAvailable":  "No",
        "whatsAppMessage":  "مرحبًا، أود الاستفسار عن كود المنتج: AY-K01 (كرسي حلاقة أطفال شكل سيارة ) المعروض على موقعكم.",
        "seoTitle":  "كرسي حلاقة أطفال سيارة | مصنع أولاد يحيى",
        "seoDescription":  "كرسي حلاقة أطفال بتصميم جذاب وأمان تام لتسهيل عمل الحلاق وتسلية الأطفال.",
        "keywords":  "كرسي حلاقة أطفال, كراسي أطفال صالونات, أولاد يحيى"
    },
    {
        "id":  "BC-017",
        "code":  "AY-14C",
        "name":  "كرسى موزه",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Hidden",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "6000",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-007",
        "code":  "AY-06",
        "name":  "دبابه فك وتركيب بالكامل دواسه كاوتش",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Hidden",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "3700",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-008",
        "code":  "AY-07",
        "name":  "تفاحه دواسه معدن",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Hidden",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "5400",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-011",
        "code":  "AY-11",
        "name":  "كريستال دواسه معدن",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Hidden",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "5800",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-006",
        "code":  "AY-05",
        "name":  "كرسى لوكس دواسه كوتش ثابت",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Hidden",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "3500",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-035",
        "code":  "AY-LUX30",
        "name":  "ملكى حديث",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "الكرسي الملكي المصري الكلاسيك – الفخامة البريميوم اللي حققت المعادلة الصعبة من مصنع أولاد يحيى!\r\n\r\nتحفة فنية بتصميم كلاسيكي ملكي يضيف هيبة وأناقة لأي باربر شوب؛ جودة تصنيع ومتانة تفوق المستورد، مزود ببستم هيدروليك سلس، إمالة ظهر كاملة لخدمات الدقن والتنظيف، وتنجيد كابوتنيه بإسفنج عالي الكثافة وجلد متين ضد التقشير بأعلى قيمة مقابل أفضل سعر.",
        "fullDescription":  "الكرسي الملكي المصري الكلاسيك | مصنع أولاد يحيى لتصنيع كراسي الحلاقة\r\n\r\nالموديل اللي أثبت كفاءته وحقق المعادلة الصعبة: فخامة المظهر + قوة التحمل + سعر المصنع المباشر. صُمم الكرسي الملكي ليوفر تجربة حلاقة استثنائية من الدرجة الأولى لزبونك مع سهولة وتحكم كامل للحلاق أثناء ساعات العمل الطويلة.\r\n\r\nأهم مواصفات ومميزات الموديل الملكي:\r\n\r\nتصميم كلاسيكي ملكي (Premium Look): ظهر دائري أنيق وتطريز كابوتنيه ملوكي غائر يمنح الصالون طابع الفخامة والرقي، متوفر بألوان كلاسيكية متعددة (أسود مط، هافان، نبيتي معتق، بيج).\r\n\r\nهيدروليك فائق الاعتمادية: بستم رفع وخفض ناعم وقوي جداً يتحمل الأوزان الثقيلة مع دوران كامل 360 درجة وثبات تام.\r\n\r\nإمالة مرنة للظهر: ذراع تحكم جانبي يتيح نزول الظهر بزاوية استلقاء مريحة ومثالية لجلسات الدقن، الفتلة، والماسك وتنظيف البشرة.\r\n\r\nمسند رأس مريح: مخدة رأس قابلة للرفع، التنزيل، أو الفك تماماً حسب طول العميل وراحة الرقبة.\r\n\r\nتنجيد وإسفنج عالي الكثافة: إسفنج صب متين لا يهبط بمرور الوقت ويوفر راحة تدوم طوال فترة الجلسة.\r\n\r\nجلد مستورد ضد التقشير: خامة جلد ممتازة شديدة التحمل ومقاومة للاحتكاك وسهلة التنظيف والتعقيم اليومي.\r\n\r\nقاعدة صينية متزنة: قاعدة دائرية ثقيلة تمنع أي اهتزاز أثناء الشغل مع دعامات كاوتش سفلية لحماية الأرضيات ومنع الانزلاق.\r\n\r\n📞 للحجز والاستفسار وطلب الأوردر:\r\n\r\nتواصل معنا مباشرة عبر الهاتف أو واتساب: 201008355616+\r\n\r\n🌐 لمشاهدة باقي موديلات المصنع والكتالوج بالكامل:\r\n\r\nhttps://wa.me/c/201064116703\r\n\r\n📲 تابعونا على صفحة الفيسبوك:\r\n\r\nhttps://www.facebook.com/YahiaSonsCosmetics\r\n\r\n📢 قناتنا الرسمية على التليجرام:\r\n\r\nhttps://t.me/YahiaSons",
        "status":  "Available",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "8700",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-004",
        "code":  "AY-03",
        "name":  "كرسى دبابه ثابت دواسه كوتش",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Hidden",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "3400",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    },
    {
        "id":  "BC-005",
        "code":  "AY-04",
        "name":  "كرسى دبابه بيلف دواسه كوتش",
        "category":  "BC",
        "categoryName":  "كراسي حلاقة وكوافير",
        "shortDesc":  "",
        "fullDescription":  "",
        "status":  "Hidden",
        "featured":  "No",
        "displayOrder":  999,
        "price":  "3650",
        "showPrice":  "Yes",
        "image":  "assets/images/chair-mens-classic.svg",
        "images":  [
                       "assets/images/chair-mens-classic.svg"
                   ],
        "specifications":  "",
        "materials":  "",
        "availableColors":  "",
        "customizationAvailable":  "Yes",
        "whatsAppMessage":  "",
        "seoTitle":  "",
        "seoDescription":  "",
        "keywords":  ""
    }
];
